// app/Components/Vue/components/Tabs.vue
<template>
  <div
    :class="\`Navigation-tabs theme-${theme} size-${size} variant-${variant}${disabled ? ' disabled' : ''}\`"
  >
    <div v-if="title" class="font-bold mb-2">{{ title }}</div>
    <div v-if="content" class="content">{{ content }}</div>
    <slot></slot>
  </div>
</template>

<script>
export default {
  name: 'Tabs',
  props: {
    title: { type: String, default: null },
    content: { type: [String, Object], default: null },
    variant: { type: String, default: 'base' },
    size: { type: String, default: 'md' },
    theme: { type: String, default: 'default' },
    disabled: { type: Boolean, default: false },
  },
};
</script>

// app/Components/React/components/Tabs.jsx
import React from 'react';
import PropTypes from 'prop-types';

const Tabs = ({ title, content, variant = 'base', size = 'md', theme = 'default', disabled = false, children, ...props }) => {
    const className = \`Navigation-Tabs theme-${theme} size-${size} variant-${variant}${disabled ? ' disabled' : ''}\`;

    return (
        <div className={className} role="button" aria-label={title} {...props}>
            {title && <div className="font-bold mb-2">{title}</div>}
            {content && <div className="content">{content}</div>}
            {children}
        </div>
    );
};

Tabs.propTypes = {
    title: PropTypes.string,
    content: PropTypes.node,
    variant: PropTypes.string,
    size: PropTypes.string,
    theme: PropTypes.string,
    disabled: PropTypes.bool,
    children: PropTypes.node,
};

export default Tabs;
